[build]
builder = "dockerfile"

[build.args]
APP_NAME = "$APP_NAME"
APP_ENV = "$APP_ENV"
APP_KEY = "$APP_KEY"
APP_DEBUG = "$APP_DEBUG"
APP_URL = "$APP_URL"

DB_CONNECTION = "$DB_CONNECTION"
DB_HOST = "$DB_HOST"
DB_PORT = "$DB_PORT"
DB_DATABASE = "$DB_DATABASE"
DB_USERNAME = "$DB_USERNAME"
DB_PASSWORD = "$DB_PASSWORD"

LOG_CHANNEL = "$LOG_CHANNEL"
LOG_LEVEL = "$LOG_LEVEL"

SESSION_DRIVER = "$SESSION_DRIVER"
CACHE_STORE = "$CACHE_STORE"
QUEUE_CONNECTION = "$QUEUE_CONNECTION"
FILESYSTEM_DISK = "$FILESYSTEM_DISK"
