[build]
builder = "nixpacks"
buildCommand = "php83 artisan l5-swagger:generate || true"

[build.env]
PHP_VERSION = "8.3"

[build.nixpacks]
packages = [
    "php83",
    "php83Extensions.curl",
    "php83Extensions.mbstring",
    "php83Extensions.pdo",
    "php83Extensions.pdo_pgsql",
    "php83Extensions.fileinfo",
    "php83Extensions.openssl",
    "php83Extensions.dom",
    "php83Extensions.xml",
    "php83Extensions.tokenizer",
    "php83Extensions.session"
]

[deploy]
startCommand = "rm -f bootstrap/cache/*.php && chmod -R 777 storage bootstrap/cache && php83 -S 0.0.0.0:${PORT} -t public/"
